-- 给 sensor_data 表添加 GPS 字段
ALTER TABLE sensor_data
  ADD COLUMN IF NOT EXISTS lat DOUBLE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS lng DOUBLE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS alt DOUBLE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS spd DOUBLE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS sat INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS fix INT DEFAULT NULL;
